from __future__ import annotations

import time
from typing import Any

from PIL import Image
from langchain.agents import create_agent
from langchain.agents.middleware import wrap_model_call
from langchain_core.messages import AIMessage, ToolMessage
from langgraph.errors import GraphRecursionError

from agent.messages import build_user_message
from agent.prompts import PREVIEW_PROMPT, UNIFIED_PROMPT
from agent.run import AgentRun
from agent.tools import build_tools
from prompts import (RAG_PROMPT, RAG_PROMPT_DIRECT, RAG_PROMPT_LEGACY,
                     extract_answer)
from retrieval.bm25 import BM25Ranker
from retrieval.fusion import Ranking, rank_paragraphs


def open_text_gate(state: dict, tool_name: str, threshold: float) -> Any:
    """Force ``tool_name`` only where the pool looks like it lacks the answer.

    The agentic version of the pipeline's second round, and the same trigger: a
    measured score rather than the model's own sense of whether it has enough,
    which failed in five separate experiments. What differs from the pipeline is
    the query — the agent writes `Phyllanthus niruri` where the pipeline can
    only pass "this plant", and this channel lives on rare words.
    """
    @wrap_model_call
    def middleware(request, handler):
        score = state.get("top_score")
        if score is not None and score < threshold:
            state["gate_below"] = state.get("gate_below", 0) + 1
            if should_force(request.messages, tool_name):
                state["forced"] = state.get("forced", 0) + 1
                return handler(request.override(tool_choice=tool_name))
        return handler(request)

    return middleware


def should_force(messages, tool_name: str) -> bool:
    """True while the agent has read a tool result but never called ``tool_name``.

    Split out of the middleware so it can be tested without a model: the last
    version of this shipped with an undefined name and failed on all 1000
    examples, which a two-line check would have caught.
    """
    if not any(isinstance(m, ToolMessage) for m in messages):
        return False        # nothing read yet: too early to demand a second round
    called = sum(1 for m in messages if isinstance(m, AIMessage)
                 for tc in (m.tool_calls or []) if tc["name"] == tool_name)
    return called == 0


class AgenticRAG:
    """Runs the agentic RAG loop for one example at a time.

    Tools retrieve on demand and grow a per-example working set of articles; the
    model decides whether to enter by name or by image, and which to read.
    """

    def __init__(self, llm, retriever, kb, reranker,
                 ranking: Ranking = Ranking(), top_k=20, max_iterations=8,
                 text_limit: int = 5, max_names: int = 4, lookup_limit: int = 3,
                 text_gate: float | None = None,
                 final_pass: bool = False, legacy_prompt: bool = False,
                 direct_prompt: bool = False, preview: int = 0):
        self.llm = llm
        self.retriever = retriever
        self.kb = kb
        self.reranker = reranker
        self.bm25 = BM25Ranker()
        self.ranking = ranking
        self.top_k = top_k
        self.max_iterations = max_iterations
        self.text_limit = text_limit
        self.max_names = max_names
        self.lookup_limit = lookup_limit
        self.text_gate = text_gate
        self.final_pass = final_pass
        self.legacy_prompt = legacy_prompt
        self.direct_prompt = direct_prompt
        self.preview = preview

    def _middleware(self, question: str, state: dict) -> list[Any]:
        """The one middleware left, and the only one that ever earned its place.

        Three others were removed after measuring them: forcing the first tool
        call (0.318 against 0.321 with it off, and the same first-tool
        distribution), repeating the question after every tool result, and
        requiring a specific tool before answering. All three existed to patch
        habits of the agent — not calling tools, losing the question, ignoring
        the answer format — and became pointless once the architecture stopped
        producing those habits: one tool instead of five, and the answer
        generated by the pipeline.

        This one is different in kind. It does not correct the model, it decides
        when a second retrieval round is worth it, from the cross-encoder's own
        score rather than from the model's sense of whether it knows enough —
        which failed in five separate experiments.
        """
        if self.text_gate is None:
            return []
        return [open_text_gate(state, "search", self.text_gate)]

    def run(self, image_path: str, question: str) -> AgentRun:
        t0 = time.time()

        state: dict = {}   # per example: the tools write into it, the middleware reads

        try:
            image = Image.open(image_path).convert("RGB")
        except Exception as e:
            return AgentRun(error=f"Image load error: {str(e)}")
        
        agent = create_agent(
            model=self.llm,
            tools=build_tools(self.retriever, self.kb, self.reranker, self.bm25,
                              image, top_k=self.top_k,
                              ranking=self.ranking,
                              text_limit=self.text_limit,
                              max_names=self.max_names,
                              lookup_limit=self.lookup_limit,
                              state=state,
                              preview=self.preview, question=question),
            system_prompt=PREVIEW_PROMPT if self.preview else UNIFIED_PROMPT,
            middleware=self._middleware(question, state),
        )

        try:
            out = agent.invoke(
                {"messages": [build_user_message(image_path, question)]},
                config={"recursion_limit": 2 * self.max_iterations + 1},
            )
            run = AgentRun.from_messages(out["messages"])
            run.messages = out["messages"]
        except GraphRecursionError:
            run = AgentRun(error="recursion_limit")
        except Exception as e:
            run = AgentRun(error=str(e))

        if self.final_pass and not run.error:
            answer = self._answer_from_pool(image_path, question, state)
            if answer is not None:
                run.prediction = answer

        run.gate_below = state.get("gate_below", 0)
        run.forced = state.get("forced", 0)
        run.elapsed_seconds = round(time.time() - t0, 2)
        return run

    def _answer_from_pool(self, image_path: str, question: str, state: dict):
        """Answer from the pool the agent assembled, the way baseline B does.

        The agent retrieves as well as the pipeline and answers worse: with the
        same channels, gate and reranker it holds the right answer in 30.3% of
        its replies against 33.3%, while reading the same paragraphs. This keeps
        its retrieval and hands the reading back to a single call over one block
        of passages, which is the only part of B it was losing to.
        """
        candidates = state.get("candidates") or {}
        pooled = [p for c in candidates.values()
                  for p in self.kb.get_paragraphs_by_url(
                      wiki_url=c.wiki_url)]
        if not pooled:
            return None
        best = rank_paragraphs(question, pooled, strategy=self.ranking.final,
                               top_k=self.ranking.top_n, reranker=self.reranker,
                               bm25_ranker=self.bm25,
                               bm25_top_m=self.ranking.bm25_top_m,
                               rrf_k=self.ranking.rrf_k)
        if not best:
            return None
        template = (RAG_PROMPT_DIRECT if self.direct_prompt else
                    RAG_PROMPT_LEGACY if self.legacy_prompt else RAG_PROMPT)
        prompt = template.format(context="\n\n".join(best), question=question)
        reply = self.llm.invoke([build_user_message(image_path, prompt)]).content
        return extract_answer(reply if isinstance(reply, str) else str(reply))
